spring:
  application:
    name: right-hand
  datasource:
    url: jdbc:postgresql://localhost:5432/right_hand
    username: right_hand
    password: right_hand
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
